[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path="2022/lib.rs"

[[bin]]
name="2022"
path="2022/main.rs"

[dependencies]
