#include <catch2/catch_test_macros.hpp>

#include "twenty_five/day_07.h"

const std::string test_input =
    R"(.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............)";

TEST_CASE("Day 07 - Part 1") {
  std::string result = day_07::part1(test_input);
  REQUIRE(result == "21");
}

TEST_CASE("Day 07 - Part 2") {
  std::string result = day_07::part2(test_input);
  REQUIRE(result == "40");
}
