from twenty_four import day_08

input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

def test_part_one():
    assert day_08.part_one(input) == 14

def test_part_two():
    assert day_08.part_two(input) == 34